# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|  
  config.vm.box = "ubuntu-precise_14.04_x64"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"  
  
  config.vm.define "attacker" do |attacker|
    attacker.vm.network "private_network", ip: "10.10.10.10"
    attacker.vm.provider :virtualbox do |vb|
      vb.name = "attacker"
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", "256"]
    end
    attacker.vm.provision "shell", path: 'provision.sh', privileged: "true"
  end  
end