- hosts: firewall_1
  roles:  
  - role: tersmitten.keepalived
    keepalived_vrrp_scripts:
      chk_haproxy:
        script: 'killall -0 haproxy'
        weight: 2
        interval: 1
    keepalived_vrrp_instances:
      VI_1:
        interface: eth1
        state: MASTER
        priority: 101
        virtual_router_id: 84
        authentication:
          auth_type: PASS
          auth_pass: 'password'
        virtual_ipaddresses:
        - '192.168.10.254 dev eth1 label eth1:1'
        track_scripts:
        - chk_haproxy

- hosts: firewall_2
  roles:  
  - role: tersmitten.keepalived
    keepalived_vrrp_scripts:
      chk_haproxy:
        script: 'killall -0 haproxy'
        weight: 2
        interval: 1
    keepalived_vrrp_instances:
      VI_1:
        interface: eth1
        state: MASTER
        priority: 100
        virtual_router_id: 84
        authentication:
          auth_type: PASS
          auth_pass: 'password'
        virtual_ipaddresses:
        - '192.168.10.254 dev eth1 label eth1:1'
        track_scripts:
        - chk_haproxy

- hosts: firewalls
  tasks:
  - name: Allow ip forwarding
    shell: sysctl net.ipv4.ip_forward=1
  roles:
  - role: geerlingguy.firewall
    firewall_allowed_tcp_ports:
    - "22"
    - "443"
    firewall_additional_rules:    
    - "iptables -A FORWARD -m limit -j LOG"
    - "iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination 192.168.10.200:443"
    - "iptables -t nat -A POSTROUTING -j MASQUERADE"

  - role: tersmitten.fail2ban
    fail2ban_destemail: mikael.gibert@yopmail.com
    fail2ban_action: action_mwl
    fail2ban_ignore_ip: 127.0.0.1/8 192.168.10.0/24
    fail2ban_bantime: 60
    fail2ban_services:
    - name: ssh
      enabled: true
      port: ssh
      filter: sshd
      logpath: /var/log/auth.log
      maxretry: 3
