- hosts: ssl_terminators
  roles:  
  - role: migibert.stunnel
    stunnel_certificate_generation: True
    stunnel_certificate_duration: 365
    stunnel_certificate_domain: www.domain.com
    stunnel_certificate_country: FR
    stunnel_certificate_organization: organization
    stunnel_certificate_state_name: state
    stunnel_certificate_locality: locality
    stunnel_certificate_file: /tmp/certificate.pem
    stunnel_key_file: /tmp/key.pem
    stunnel_services:
    - service:
      name: https
      accept: 443
      connect: 192.168.10.100:80